# Generated by Django 3.0.6 on 2020-05-28 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_title', models.CharField(max_length=200)),
                ('tutorial_published', models.DateTimeField(default=datetime.datetime(2020, 5, 28, 18, 17, 0, 885700), verbose_name='date published')),
                ('tutorial_content', models.TextField()),
            ],
        ),
    ]
